#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    flutter test
else
  rootPath=$(pwd)
  
  for path in "$@"; do
    cd "$path" || exit

    if ! flutter test; then
      exit $?
    fi

    cd "$rootPath" || exit
  done
fi

